version: "3.4"
networks:
  #可以自定义network名称，这里使用default表示如果不在service中单独配置就使用该设置 
  default: 
    external: 
      name: app-net
services:
  monitor1:
    image: xlvchao/spartacus-monitor:1.0.0
    container_name: monitor1
    restart: always
    environment:
      - JAVA_OPTS=-server -Xms128M -Xmx256M -Xmn64M -XX:MetaspaceSize=64M -XX:MaxMetaspaceSize=128M
      - instanceIp=10.0.0.10
      - instancePort=4001
      - xxlJobExecutorPort=4011
      - APOLLO_META="http://10.0.0.11:8080,http://10.0.0.9:8081,http://10.0.0.16:8082"
      - APOLLO_ACCESSKEY_SECRET=31b4fb83736b4f4cb865673f5197d160
    volumes:
      - /opt/settings:/opt/settings
    ports:
      - 4001:4001
      - 4011:4011
#  monitor2:
#    image: xlvchao/spartacus-monitor:1.0.0
#    container_name: monitor2
#    restart: always
#    environment:
#      - JAVA_OPTS=-server -Xms128M -Xmx256M -Xmn64M -XX:MetaspaceSize=64M -XX:MaxMetaspaceSize=128M
#      - instanceIp=10.0.0.4
#      - instancePort=4002
#      - xxlJobExecutorPort=4012
#      - APOLLO_META="http://10.0.0.11:8080,http://10.0.0.9:8081,http://10.0.0.16:8082"
#      - APOLLO_ACCESSKEY_SECRET=31b4fb83736b4f4cb865673f5197d160
#    volumes:
#      - /opt/settings:/opt/settings
#    ports:
#      - 4002:4002
#      - 4012:4012
#  monitor3:
#    image: xlvchao/spartacus-monitor:1.0.0
#    container_name: monitor3
#    restart: always
#    environment:
#      - JAVA_OPTS=-server -Xms128M -Xmx256M -Xmn64M -XX:MetaspaceSize=64M -XX:MaxMetaspaceSize=128M
#      - instanceIp=10.0.0.14
#      - instancePort=4003
#      - xxlJobExecutorPort=4013
#      - APOLLO_META="http://10.0.0.11:8080,http://10.0.0.9:8081,http://10.0.0.16:8082"
#      - APOLLO_ACCESSKEY_SECRET=31b4fb83736b4f4cb865673f5197d160
#    volumes:
#      - /opt/settings:/opt/settings
#    ports:
#      - 4003:4003
#      - 4013:4013